2024-01-04 14:06:59,203 ERROR: Exception on / [GET] [in C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2421, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\sql\util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\sql\selectable.py", line 1357, in _join_condition
    cls._joincond_trim_constraints(
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\sql\selectable.py", line 1502, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'user' and 'todo'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\werkzeug\local.py", line 316, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\werkzeug\local.py", line 520, in _get_current_object
    return get_name(local())  # type: ignore
                    ^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\flask_login\utils.py", line 372, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\app\models.py", line 88, in load_user
    return User.query.get(int(id))
           ^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\flask_sqlalchemy\model.py", line 30, in __get__
    return cls.query_class(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 273, in __init__
    self._set_entities(entities)
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 282, in _set_entities
    self._raw_columns = [
                        ^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 283, in <listcomp>
    coercions.expect(
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\sql\coercions.py", line 406, in expect
    insp._post_inspect
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1254, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2693, in _post_inspect
    self._check_configure()
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2374, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4186, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4228, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2391, in _post_configure_properties
    prop.init()
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 544, in init
    self.do_init()
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1634, in do_init
    self._setup_join_conditions()
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1881, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2308, in __init__
    self._determine_joins()
  File "C:\Users\Gio\Documents\GitHub\planner\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2465, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.todos - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.
